---
- name: Render Jinja template
  hosts: localhost
  tasks:
    - name: Assert that red_env is provided
      assert:
        that:
          - red_env is defined
        fail_msg: "The red_env variable must be provided!"

    - name: Assert that enable_test_route is provided
      assert:
        that:
          - enable_test_route is defined
        fail_msg: "The enable_test_route variable must be provided!"

    - name: Ensure /etc/nginx/conf.d/ exists
      file:
        path: /etc/nginx/conf.d
        state: directory
        mode: "0755"

    - name: Render the frontend Jinja template
      tags: [frontend]
      template:
        src: templates/nginx.frontendConfig.j2
        dest: /etc/nginx/conf.d/frontendConfig.conf

    - name: Render the backend Jinja template
      tags: [backend]
      template:
        src: templates/nginx.backendConfig.j2
        dest: /etc/nginx/conf.d/backendConfig.conf
